with-expecter: true
dir: testing/mocks/{{ replaceAll .InterfaceDirRelative "internal" "internal_"}}
filename: "{{.InterfaceName}}.go"
mockname: "Mock{{.InterfaceName}}"
outpkg: "{{.PackageName}}"
all: true
recursive: true
packages:
  github.com/growteer/api/internal/app:
  github.com/growteer/api/internal/entities:
  github.com/growteer/api/internal/infrastructure:
  github.com/growteer/api/internal/repository:
  github.com/growteer/api/pkg:
