# Only for local testing!
version: "3.9"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
    environment:
      MONGO_INITDB_DATABASE: api_service
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      growteer_network:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - mongodb
    environment:
      ALLOWED_ORIGINS: http://localhost:3000
      MONGO_DB_NAME: api_service
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_USER: admin
      MONGO_PASSWORD: password
      MONGODB_CONNECTION_STRING: mongodb://admin:password@mongodb:27017/?ssl=false
      JWT_SECRET: baconkilbasa
      SESSION_TTL_MINUTES: 60
    networks:
      growteer_network:

volumes:
  mongodb:

networks:
  growteer_network:
