schema = 3

[mod]
  [mod."filippo.io/edwards25519"]
    version = "v1.0.0-rc.1"
    hash = "sha256-3DboBqby2ejRU33FG96Z8JF5AJ8HP2rC/v++VyoQ2LQ="
  [mod."github.com/99designs/gqlgen"]
    version = "v0.17.60"
    hash = "sha256-F4oS6rz18zjqYu2WEFrWwOauir8QA5F9MhDMbvJVkwM="
  [mod."github.com/agnivade/levenshtein"]
    version = "v1.2.0"
    hash = "sha256-Fg6SxKFiJL5xqnVsiLsCcp6XasbBiIuxNWljMpNU6W0="
  [mod."github.com/blendle/zapdriver"]
    version = "v1.3.1"
    hash = "sha256-SSRaX/YcLFRf3BD/TGjpupGQ0HxFdP1SHyrZNw767IQ="
  [mod."github.com/davecgh/go-spew"]
    version = "v1.1.1"
    hash = "sha256-nhzSUrE1fCkN0+RL04N4h8jWmRFPPPWbCuDc7Ss0akI="
  [mod."github.com/fatih/color"]
    version = "v1.16.0"
    hash = "sha256-Aq/SM28aPJVzvapllQ64R/DM4aZ5CHPewcm/AUJPyJQ="
    replaced = "github.com/fatih/color"
  [mod."github.com/gagliardetto/binary"]
    version = "v0.8.0"
    hash = "sha256-Szn+6wdBfOHPNxXCHL8roOirkGnhyWntz405HxtLbic="
  [mod."github.com/gagliardetto/solana-go"]
    version = "v1.12.0"
    hash = "sha256-+Ksz4QU/PLQ9n+DNWKl8w506uTVCgRmulItBZr0wx+0="
  [mod."github.com/gagliardetto/treeout"]
    version = "v0.1.4"
    hash = "sha256-odFC2amCEPmZvdK4lfuox2njpt6fqIR0Z0eRtWlDxAM="
  [mod."github.com/go-chi/chi/v5"]
    version = "v5.2.2"
    hash = "sha256-F+KxLJNRQxkjQCDlJ72MT/YS8cybKPsLeWOjo6HqJHU="
  [mod."github.com/go-viper/mapstructure/v2"]
    version = "v2.3.0"
    hash = "sha256-1aAH3Iqp8ntSFoMT1NrgDBaKJ6UOjw/1/dzePIF2nR4="
  [mod."github.com/golang-jwt/jwt/v5"]
    version = "v5.2.2"
    hash = "sha256-C0MhDguxWR6dQUrNVQ5xaFUReSV6CVEBAijG3b4wnX4="
  [mod."github.com/golang/snappy"]
    version = "v0.0.5-0.20220116011046-fa5810519dcb"
    hash = "sha256-4GVLPBwJIXYFJU+Uvoa/sb5VHea7yJhwE7feABa7ucs="
  [mod."github.com/google/uuid"]
    version = "v1.6.0"
    hash = "sha256-VWl9sqUzdOuhW0KzQlv0gwwUQClYkmZwSydHG2sALYw="
  [mod."github.com/gorilla/websocket"]
    version = "v1.5.0"
    hash = "sha256-EYVgkSEMo4HaVrsWKqnsYRp8SSS8gNf7t+Elva02Ofc="
  [mod."github.com/hashicorp/golang-lru/v2"]
    version = "v2.0.7"
    hash = "sha256-t1bcXLgrQNOYUVyYEZ0knxcXpsTk4IuJZDjKvyJX75g="
  [mod."github.com/joho/godotenv"]
    version = "v1.5.1"
    hash = "sha256-kA0osKfsc6Kp+nuGTRJyXZZlJt1D/kuEazKMWYCWcQ8="
  [mod."github.com/json-iterator/go"]
    version = "v1.1.12"
    hash = "sha256-To8A0h+lbfZ/6zM+2PpRpY3+L6725OPC66lffq6fUoM="
  [mod."github.com/klauspost/compress"]
    version = "v1.17.4"
    hash = "sha256-5E7dDtDKfL3jy7zJxHBMV57WlHZrP/OoEX5e6cOPba0="
  [mod."github.com/kr/pretty"]
    version = "v0.3.1"
    hash = "sha256-DlER7XM+xiaLjvebcIPiB12oVNjyZHuJHoRGITzzpKU="
  [mod."github.com/logrusorgru/aurora"]
    version = "v2.0.3+incompatible"
    hash = "sha256-7o5Fh4jscdYKgXfnNMbcD68Kjw8Z4LcPgHcr4ZyQYrI="
  [mod."github.com/mattn/go-colorable"]
    version = "v0.1.14"
    hash = "sha256-JC60PjKj7MvhZmUHTZ9p372FV72I9Mxvli3fivTbxuA="
    replaced = "github.com/mattn/go-colorable"
  [mod."github.com/mattn/go-isatty"]
    version = "v0.0.20"
    hash = "sha256-qhw9hWtU5wnyFyuMbKx+7RB8ckQaFQ8D+8GKPkN3HHQ="
  [mod."github.com/mitchellh/go-testing-interface"]
    version = "v1.14.1"
    hash = "sha256-TMGi38D13BEVN5cpeKDzKRIgLclm4ErOG+JEyqJrN/c="
  [mod."github.com/modern-go/concurrent"]
    version = "v0.0.0-20180306012644-bacd9c7ef1dd"
    hash = "sha256-OTySieAgPWR4oJnlohaFTeK1tRaVp/b0d1rYY8xKMzo="
  [mod."github.com/modern-go/reflect2"]
    version = "v1.0.2"
    hash = "sha256-+W9EIW7okXIXjWEgOaMh58eLvBZ7OshW2EhaIpNLSBU="
  [mod."github.com/montanaflynn/stats"]
    version = "v0.7.1"
    hash = "sha256-0QXUA/syOtDSBooh3isAffrVAjpSoBmSMMuZfO5maHg="
  [mod."github.com/mostynb/zstdpool-freelist"]
    version = "v0.0.0-20201229113212-927304c0c3b1"
    hash = "sha256-P9ksvx6IcHo4L44PDcSpt6BWowPwkiIB6P0blB84MZc="
  [mod."github.com/mr-tron/base58"]
    version = "v1.2.0"
    hash = "sha256-8FzMu3kHUbBX10pUdtGf59Ag7BNupx8ZHeUaodR1/Vk="
  [mod."github.com/pmezard/go-difflib"]
    version = "v1.0.0"
    hash = "sha256-/FtmHnaGjdvEIKAJtrUfEhV7EVo5A/eYrtdnUkuxLDA="
  [mod."github.com/rs/cors"]
    version = "v1.11.1"
    hash = "sha256-0z4aFR5VjuVYn+XnANbjui0ADcdG7gU56A9Y/NtrzCQ="
  [mod."github.com/sosodev/duration"]
    version = "v1.3.1"
    hash = "sha256-4TQS0p7FjTztG7P3VJDEaWLHHEOUADFwgEswuh/obb0="
  [mod."github.com/streamingfast/logging"]
    version = "v0.0.0-20230608130331-f22c91403091"
    hash = "sha256-ucpmtSeDGcV6HHCvE782XhkaZe4xKieWFdmVaA9PDjA="
  [mod."github.com/stretchr/objx"]
    version = "v0.5.2"
    hash = "sha256-VKYxrrFb1nkX6Wu3tE5DoP9+fCttwSl9pgLN6567nck="
  [mod."github.com/stretchr/testify"]
    version = "v1.10.0"
    hash = "sha256-fJ4gnPr0vnrOhjQYQwJ3ARDKPsOtA7d4olQmQWR+wpI="
  [mod."github.com/vektah/gqlparser/v2"]
    version = "v2.5.20"
    hash = "sha256-jkHpt9vF+QSAdN7kNLoIr6vViMFOvbGxI8feZbuOwF0="
  [mod."github.com/vrischmann/envconfig"]
    version = "v1.3.0"
    hash = "sha256-OLPild6/eKWBOCrBHUlNY1MS1l+8QBLfsNVC66fD8LY="
  [mod."github.com/xdg-go/pbkdf2"]
    version = "v1.0.0"
    hash = "sha256-UKK8JrdxEeToqs53sUUMUZNQv8w+lzuhd7bNXryMN9o="
  [mod."github.com/xdg-go/scram"]
    version = "v1.1.2"
    hash = "sha256-BPlloFojiFA8TiYIaBPW9BFBNkCmYD68JrY5gry1f64="
  [mod."github.com/xdg-go/stringprep"]
    version = "v1.0.4"
    hash = "sha256-zGNSty2K8PoqMw71AHPvICuUvIzXzUvCW+fCNr3XmLE="
  [mod."github.com/youmark/pkcs8"]
    version = "v0.0.0-20240726163527-a2c0da244d78"
    hash = "sha256-7ETUt8onE9mdUlvHT5xxzfh8mK0qw15ZSYXQCtah9p4="
  [mod."go.mongodb.org/mongo-driver"]
    version = "v1.17.1"
    hash = "sha256-/0TG8G5SHfaRPnCH9L2Nc73JnhZZhb64TJ1pz1x2sHk="
  [mod."go.uber.org/atomic"]
    version = "v1.7.0"
    hash = "sha256-g83RSzO/5k8W3qyiIsrQbVq1F8qJGccdWEXTjkqUOfc="
  [mod."go.uber.org/goleak"]
    version = "v1.1.12"
    hash = "sha256-7++AVgDu59zNKqxEQHnao2bLmHlU5Pum3nbhXtoaqvE="
  [mod."go.uber.org/multierr"]
    version = "v1.6.0"
    hash = "sha256-X+l7OPAkMhpw+5VvFWuQ/DfTCSjQH/8VvSoQrb44CEU="
  [mod."go.uber.org/zap"]
    version = "v1.21.0"
    hash = "sha256-ZqIYkENfis3vlN4Z1Ejdn9Nn0pU89tHtcAYcR+b2Kb0="
  [mod."golang.org/x/crypto"]
    version = "v0.36.0"
    hash = "sha256-Np+suvZdMOXALDm4m8nDNa+QsvUV0rE0PEINuxCoKGM="
  [mod."golang.org/x/net"]
    version = "v0.38.0"
    hash = "sha256-iHmyxkZQLw1PsUZaXHMt84GrjbXPvkEc92sLoK3W++c="
  [mod."golang.org/x/sync"]
    version = "v0.12.0"
    hash = "sha256-lPIbI6aXx+iKtFjPaXKNLEnuNfhHCVl7EQiE7alUvlM="
  [mod."golang.org/x/sys"]
    version = "v0.31.0"
    hash = "sha256-aulv5obCrhheMlSq7seUgP3C29nfZABwiQ4IBNisgME="
  [mod."golang.org/x/term"]
    version = "v0.30.0"
    hash = "sha256-bgN4cMED7P2SqFZQZPNRPJL2Px35chNoWaqNhLDEoZM="
  [mod."golang.org/x/text"]
    version = "v0.23.0"
    hash = "sha256-TiYX1K4DYpP1dEV06whOm43xyOntjrPFi+VAdncoeCY="
  [mod."gopkg.in/check.v1"]
    version = "v1.0.0-20201130134442-10cb98267c6c"
    hash = "sha256-VlIpM2r/OD+kkyItn6vW35dyc0rtkJufA93rjFyzncs="
  [mod."gopkg.in/yaml.v2"]
    version = "v3.0.1"
    hash = "sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU="
    replaced = "gopkg.in/yaml.v3"
