version: "3"

vars:
  BIN: "{{ .TASKFILE_DIR }}/bin"

tasks:
  build:
    cmds:
      - cmd: |
          go build \
            -tags release \
            -o {{.BIN}}/main \
            ./cmd/main.go;
    env:
      CGO_ENABLED: 0
      GOOS: linux
      GOARCH: amd64

  run:
    cmds:
      - go run ./cmd/main.go
    env:
      HTTP_PORT: 8080
      MONGO_HOST: localhost
      MONGO_PORT: 27017
      MONGO_USER: admin
      MONGO_PASSWORD: password
      MONGO_DB_NAME: api_service
      MONGO_SSL: false
      JWT_SECRET: baconkilbasa
      SESSION_TTL_MINUTES: 60

  debug:
    cmd: |
      go run github.com/go-delve/delve/cmd/dlv@latest debug \
        ./cmd/main.go \
        --headless \
        --listen=:2345 \
        --api-version=2

  gen:
    cmds:
      - go run github.com/99designs/gqlgen generate

  db:
    cmds:
      - cmd: |
          docker run -it -p 27017:27017 \
            -e MONGO_INITDB_ROOT_USERNAME=admin \
            -e MONGO_INITDB_ROOT_PASSWORD=password \
            mongo:latest
