version: "3"

tasks:
  run:
    cmds:
      - go run ./cmd/main.go
    env:
      HTTP_PORT: 8080
      MONGO_HOST: localhost
      MONGO_PORT: 27017
      MONGO_USER: admin
      MONGO_PASSWORD: password
      MONGO_DB_NAME: api_service
      MONGO_SSL: false

  gen:
    cmds:
      - go run github.com/99designs/gqlgen generate

  db:
    cmds:
      - cmd: |
          docker run -it -p 27017:27017 \
            -e MONGO_INITDB_ROOT_USERNAME=admin \
            -e MONGO_INITDB_ROOT_PASSWORD=password \
            --name mongodb \
            mongo:latest
