apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "api.fullname" . }}
  labels:
    {{- include "api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "api.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "api.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.http.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          env:
            - name: HTTP_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "api.fullname" . }}
                  key: HTTP_PORT
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ include "api.fullname" . }}
                  key: MONGO_HOST
            - name: MONGO_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "api.fullname" . }}
                  key: MONGO_PORT
            - name: MONGO_USER
              valueFrom:
                configMapKeyRef:
                  name: {{ include "api.fullname" . }}
                  key: MONGO_USER
            - name: MONGO_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: {{ include "api.fullname" . }}
                  key: MONGO_PASSWORD
            - name: MONGO_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "api.fullname" . }}
                  key: MONGO_DB_NAME
            - name: MONGO_SSL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "api.fullname" . }}
                  key: MONGO_SSL
            - name: JWT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: {{ include "api.fullname" . }}
                  key: JWT_SECRET
            - name: SESSION_TTL_MINUTES
              valueFrom:
                configMapKeyRef:
                  name: {{ include "api.fullname" . }}
                  key: SESSION_TTL_MINUTES
