// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type LoginInput struct {
	Address   string `json:"address"`
	Message   string `json:"message"`
	Signature string `json:"signature"`
}

type Mutation struct {
}

type Nonce struct {
	Value string `json:"value"`
}

type NonceInput struct {
	Address string `json:"address"`
}

type Query struct {
}

type Session struct {
	SessionToken string `json:"sessionToken"`
}
