// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AuthResult struct {
	SessionToken string `json:"sessionToken"`
	RefreshToken string `json:"refreshToken"`
}

type LoginInput struct {
	Address   string `json:"address"`
	Message   string `json:"message"`
	Signature string `json:"signature"`
}

type Mutation struct {
}

type NonceInput struct {
	Address string `json:"address"`
}

type NonceResult struct {
	Nonce string `json:"nonce"`
}

type Query struct {
}

type RefreshInput struct {
	RefreshToken string `json:"refreshToken"`
}
