name: Integration Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Lint
        run: nix develop -c make lint

      - name: Test
        run: nix develop -c make test

      - name: Publish Test Results
        if: success() || failure()
        uses: dorny/test-reporter@v1.9.1
        with:
          name: Unit & Integration Tests
          path: reports/junit-report.xml
          reporter: java-junit

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Build
        run: nix build
